# Generated by Django 4.1.2 on 2022-10-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pengirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=12)),
                ('alamat', models.TextField(max_length=500)),
                ('kodepos', models.IntegerField(max_length=10)),
            ],
        ),
    ]
