# Generated by Django 4.1.2 on 2022-10-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengirim',
            name='kodepos',
            field=models.IntegerField(),
        ),
    ]
