# Generated by Django 4.1.2 on 2022-10-28 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jago', '0002_alter_pengirim_kodepos'),
    ]

    operations = [
        migrations.CreateModel(
            name='penerima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=12)),
                ('alamat', models.TextField(max_length=500)),
                ('kodepos', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pengirim',
            name='penerima',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jago.penerima'),
        ),
    ]
